# Generated by Django 4.1.5 on 2024-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie_stand',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cookie_stand',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookie_stand',
            name='reviewer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
