# Generated by Django 4.1.5 on 2024-03-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie_stands', '0002_cookie_stand_name_cookie_stand_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('hourly_sales', models.JSONField(default=list, null=True)),
                ('minimum_customers_per_hour', models.IntegerField(default=0)),
                ('maximum_customers_per_hour', models.IntegerField(default=0)),
                ('average_cookie_per_sale', models.FloatField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cookie_stand',
        ),
    ]
